apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpsv-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: dpsv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpsv
  template:
    metadata:
      labels:
        app: dpsv
    spec:
      {{- if or .Values.db.init .Values.persist.enabled }}
      volumes:
      {{- if .Values.db.init }}
      - name: shared-copy-volume
        emptyDir: {}
      - name: xml-init-volume
        configMap:
          name: dpsv-xml-init
      {{ end }}
      {{- if .Values.persist.enabled }}
      - name: dpsv-volume
        persistentVolumeClaim:
          claimName: dpsv-pvc
      {{ end }}
      {{ end }}
      {{- if .Values.db.init }}
      initContainers:
        - name: init-entrypoint-creator
          image: busybox:latest
          volumeMounts:
            - name: xml-init-volume
              mountPath: /source
            - name: shared-copy-volume
              mountPath: /destination
          command: ["sh", "-c"]
          args:
            - |
              for f in /source/*.zip; do unzip -d "/destination/$(basename "$f" .zip)" "$f"; done
              chmod -R 777 /destination
      {{ end }}
      containers:
      - name: dpsv-container
        image: registry.git.rwth-aachen.de/acs/public/dpsv:latest
        {{- if or .Values.db.init .Values.persist.enabled }}
        volumeMounts:
        {{- if .Values.persist.enabled }}
        - name: dpsv-volume
          mountPath: /dpsroot
        {{ end }}
        {{ if .Values.db.init }}
        - name: shared-copy-volume
          mountPath: /dpsroot/xmls
        {{ end }}
        {{ end }}
